llm_policy:
  env_params: 
    system_prompt_path: "prompts/prompt_alfworld_policy.txt"
    extract_action_regex: "optimal action: (.*)"
    prompt_buffer_prefix: "prompt_buffer/alfworld"
    save_buffer_interval: 1
  load_prompt_buffer_path: "prompt_buffer/alfworld_policy.pkl" # update this path to the path of the saved prompt buffer
  overwrite_prompt_buffer: False

  temp: 1.0

llm_mcts:
  llm_policy:
    env_params: 
      system_prompt_path: "prompts/prompt_alfworld_policy.txt"
      extract_action_regex: "optimal action: (.*)"
      prompt_buffer_prefix: "prompt_buffer/alfworld"
      save_buffer_interval: 1
    load_prompt_buffer_path: "prompt_buffer/alfworld_policy_mcts.pkl" # update this path to the path of the saved prompt buffer
    overwrite_prompt_buffer: False

  temp: 10.0

  mcts_args:
    num_simulations: 20
    c_puct: 100
    gamma: 0.99
    max_depth: 10
    num_rollouts: 1
