llm_policy:
  env_params: 
    system_prompt_path: "prompts/prompt_alfworld_policy.txt"
    extract_action_regex: "optimal action: (.*)"
    prompt_buffer_prefix: "prompt_buffer/alfworld"
    save_buffer_interval: 100

  temp: 1.0

llm_mcts:
  llm_policy:
    env_params: 
      system_prompt_path: "prompts/prompt_alfworld_policy.txt"
      extract_action_regex: "optimal action: (.*)"
      prompt_buffer_prefix: "prompt_buffer/alfworld"
      save_buffer_interval: 100

  temp: 10.0

  mcts_args:
    num_simulations: 100
    c_puct: 100
    gamma: 0.9
    max_depth: 10

mcts:
  num_simulations: 100
  c_puct: 100
  gamma: 0.9
  max_depth: 10
