llm_policy:
  env_params: 
    system_prompt_path: "prompts/prompt_elevator_policy.txt"
    extract_action_regex: "optimal action: (.*)"

  temp: 1.0

llm_mcts:
  llm_policy:
    env_params: 
      system_prompt_path: "prompts/prompt_elevator_policy.txt"
      extract_action_regex: "optimal action: (.*)"
    load_prompt_buffer_path: "prompt_buffer/elevator_20241104_023010.pkl" # update this path to the path of the saved prompt buffer
    prompt_buffer_prefix: "prompt_buffer/elevator"
    save_buffer_interval: 100

  temp: 10.0

  mcts_args:
    num_simulations: 100
    c_puct: 500
    gamma: 0.95
    max_depth: 100
    num_rollouts: 10

mcts_expert:
  mcts_args:
    num_simulations: 100
    c_puct: 100
    gamma: 0.95
    max_depth: 24